name: Ratio
main: xAliTura01\Ratio\Main
src-namespace-prefix: xAliTura01\Ratio
api: 4.0.0
author: xAliTura01
version: 0.4

permissions:
  ratio.vip:
    description: "Allow the player to Ratio vip feature"
    default: op
